services:
  postgres:
    image: postgres:16
    container_name: jm_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  minio:
    image: minio/minio:latest
    container_name: jm_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  spark-master:
    build:
      context: .
      dockerfile: spark/Dockerfile
    image: jm-spark:3.5.0-s3a
    container_name: jm_spark_master
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.master.Master",
        "--host",
        "spark-master",
        "--port",
        "7077",
        "--webui-port",
        "8080"
      ]
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    build:
      context: .
      dockerfile: spark/Dockerfile
    image: jm-spark:3.5.0-s3a
    container_name: jm_spark_worker
    depends_on:
      - spark-master
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "${SPARK_MASTER_URL}",
        "--webui-port",
        "8081"
      ]
    ports:
      - "8081:8081"

  airflow-init:
    build:
      context: ./airflow
    container_name: jm_airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment: &airflow_env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8088"
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8088
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USER}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      _AIRFLOW_WWW_USER_EMAIL: ${AIRFLOW_ADMIN_EMAIL}
      _AIRFLOW_WWW_USER_FIRSTNAME: ${AIRFLOW_ADMIN_FIRSTNAME}
      _AIRFLOW_WWW_USER_LASTNAME: ${AIRFLOW_ADMIN_LASTNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      BRONZE_BUCKET: ${BRONZE_BUCKET}
      SILVER_BUCKET: ${SILVER_BUCKET}
      SPARK_MASTER_URL: ${SPARK_MASTER_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    volumes:
      - ./:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate &&
      airflow users create
      --role Admin
      --username $${_AIRFLOW_WWW_USER_USERNAME}
      --password $${_AIRFLOW_WWW_USER_PASSWORD}
      --email $${_AIRFLOW_WWW_USER_EMAIL}
      --firstname $${_AIRFLOW_WWW_USER_FIRSTNAME}
      --lastname $${_AIRFLOW_WWW_USER_LASTNAME} || true"
    restart: "no"

  airflow-webserver:
    build:
      context: ./airflow
    container_name: jm_airflow_web
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow_env
    ports:
      - "8088:8088"
    volumes:
      - ./:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: webserver

  airflow-scheduler:
    build:
      context: ./airflow
    container_name: jm_airflow_sched
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow_env
    volumes:
      - ./:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.2
    platform: linux/amd64
    container_name: jm_dbt
    working_dir: /usr/app
    entrypoint: ["/bin/sh", "-c"]
    command: ["while true; do sleep 1000; done"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
    volumes:
      - ./dbt:/usr/app
    depends_on:
      postgres:
        condition: service_healthy

  metabase:
    image: metabase/metabase:latest
    container_name: jm_metabase
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data

volumes:
  pgdata:
  miniodata:
  metabase_data: